### ISSUE TITLE
[Bug]: Variant name is not capitalized in the Gradle task list

### ISSUE THREAD

**Issue by lihenggui** [android/nowinandroid#1008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

In the task list, you will notice that the variant name in the task is not properly capitalized. It is not a bug that will prevent users from running this task, but we'd better keep the same naming convention.

Example: 
![image](https://github.com/android/nowinandroid/assets/5171312/b5526239-459f-4e4c-8bd2-69f033f2422b)

![image](https://github.com/android/nowinandroid/assets/5171312/0802934b-3734-41ae-bf9d-40deeb2cc30f)

### Expected behavior

Variant names 'prod' and 'demo' should be capitalized correctly.

### Causes
Value in `variant.name` is not in a capitalized form
https://github.com/android/nowinandroid/pull/1001/files#diff-b32c0825279a2b8ec215b50d3147d324bc248198ceb0b352de59c47b2cd06533R105

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
